# Generated by Django 5.1 on 2026-01-04 23:22

import django.db.models.deletion
import integration.utils.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('botpress_url', models.CharField(max_length=500, verbose_name='BotPlatform URL')),
                ('botpress_username', models.CharField(max_length=255, verbose_name='BotPlatform Username')),
                ('botpress_password', integration.utils.encrypted_fields.EncryptedCharField(max_length=255, verbose_name='BotPlatform Password')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Expires At')),
                ('botpress_token', integration.utils.encrypted_fields.EncryptedTextField(blank=True, max_length=1500, null=True, verbose_name='BotPlatform_Token')),
                ('system_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='System URL')),
                ('system_auth_info', integration.utils.encrypted_fields.EncryptedTextField(blank=True, max_length=1500, null=True, verbose_name='System Auth Info')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('token', integration.utils.encrypted_fields.EncryptedCharField(blank=True, max_length=500, null=True, verbose_name='Token')),
                ('use_voice_message', models.BooleanField(default=False, verbose_name='Use Voice Message')),
                ('url_voice', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Voice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Application Configuration',
                'verbose_name_plural': 'Application Configurations',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('bot_id', models.CharField(max_length=255, verbose_name='Bot ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='User ID')),
                ('webhook_key', models.CharField(max_length=255, unique=True, verbose_name='Webhook Key')),
                ('whatsapp_provider_type', models.CharField(blank=True, choices=[('meta', 'Meta API'), ('wppconnect', 'WPPConnect')], max_length=50, null=True, verbose_name='WhatsApp Provider Type')),
                ('session', models.CharField(max_length=255, verbose_name='Session')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('auto_replay_group', models.BooleanField(default=True, verbose_name='Auto Replay In Group')),
                ('apply_authorized_contact', models.BooleanField(default=False, verbose_name='Apply Authorized Contact')),
                ('app_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Application_ID')),
                ('key_word_for_start_session', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keyword For Quick Access')),
                ('enable_keyword_start_session', models.BooleanField(default=False, verbose_name='Enable Keyword')),
                ('transfer_keywords', models.TextField(blank=True, default='حول,حوالة,ارسال حوالة,استلام حوالة,إرسال حوالة,إستلام حوالة,مدفوع,دفع,تحويل,إرسال,استلام,ارسل,استلم', help_text='Comma-separated keywords for transfer detection. Supports regex patterns.', null=True, verbose_name='Transfer Keywords')),
                ('pattern_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pattern Phone Number')),
                ('support_pattern_phone_number', models.BooleanField(default=False, verbose_name='Support Pattern Phone Number')),
                ('enable_quick_remittance', models.BooleanField(default=False, verbose_name='Enable Quick Remittance')),
                ('length_name', models.IntegerField(default=4, verbose_name='Length Name For Quick remittance')),
                ('time_zone', models.CharField(default='Asia/Aden', help_text='IANA time zone identifier used to validate incoming webhooks.', max_length=50, verbose_name='Time Zone')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.applicationconfiguration', verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
