# Generated by Django 5.1 on 2026-01-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['name'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='applicationconfiguration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Application Configuration', 'verbose_name_plural': 'Application Configurations'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='enable_quick_remittance',
        ),
        migrations.RemoveField(
            model_name='application',
            name='support_pattern_phone_number',
        ),
    ]
