# Generated by Django 5.1 on 2026-01-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_alter_application_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='enable_keyword_start_session',
        ),
        migrations.RemoveField(
            model_name='application',
            name='key_word_for_start_session',
        ),
        migrations.RemoveField(
            model_name='application',
            name='length_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='pattern_phone_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='transfer_keywords',
        ),
    ]
