# Generated by Django 5.1 on 2026-01-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_remove_application_enable_keyword_start_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='use_accounting_agent',
            field=models.BooleanField(default=False, verbose_name='Use Accounting Agent'),
        ),
    ]
