# Generated by Django 5.1 on 2026-01-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_applicationconfiguration_use_accounting_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='Session ID')),
                ('user_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Identifier')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.application', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20, verbose_name='Direction')),
                ('content', models.TextField(verbose_name='Content')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integration.conversation', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
