# Generated by Django 5.1 on 2026-01-05 18:26

import integration.utils.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='flow_ai',
            field=models.BooleanField(default=False, verbose_name='Enable Flow AI'),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='flow_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Flow ID'),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='flow_token',
            field=integration.utils.encrypted_fields.EncryptedCharField(blank=True, max_length=500, null=True, verbose_name='Flow Token'),
        ),
    ]
