# Generated by Django 5.1 on 2026-01-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_applicationconfiguration_flow_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfiguration',
            name='flow_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Flow URL'),
        ),
    ]
