# Generated by Django 5.1 on 2026-01-06 16:44

import integration.utils.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_applicationconfiguration_flow_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='User phone number (WhatsApp)', max_length=50, unique=True, verbose_name='Phone Number')),
                ('preferred_format', models.CharField(choices=[('auto', 'تلقائي - يختار النظام الأنسب'), ('text', 'نص - عرض نصي بسيط'), ('table', 'جدول - جداول منسقة'), ('paginated', 'صفحات - عرض بصفحات متعددة'), ('summary', 'ملخص - ملخص مختصر فقط')], default='auto', help_text='How the user prefers to receive data', max_length=20, verbose_name='Preferred Display Format')),
                ('max_items_per_page', models.IntegerField(default=10, help_text='Maximum number of items to show per message (5-50)', verbose_name='Items Per Page')),
                ('language', models.CharField(default='ar', help_text='Preferred language (ar/en)', max_length=10, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='applicationconfiguration',
            name='flow_token',
            field=integration.utils.encrypted_fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Flow Token'),
        ),
    ]
