# Generated by Django 5.1 on 2026-01-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0009_userpreferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Phone Number')),
                ('operation_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('sale', 'Sale'), ('create_customer', 'Create Customer')], max_length=50, verbose_name='Operation Type')),
                ('data', models.JSONField(default=dict, help_text='JSON data storing partial information for the operation', verbose_name='Collected Data')),
                ('step', models.CharField(blank=True, max_length=50, verbose_name='Current Step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pending Operation',
                'verbose_name_plural': 'Pending Operations',
            },
        ),
    ]
